module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'ci',
        'build',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'root',
        'web',
        'shared',
        'auth',
        'firebase',
        'i18n',
        'ui',
        'food',
        'school',
        'epi',
        'occ',
        'admin',
        'public',
        'mgmt',
        'ci',
        'deps',
        'types',
        'app',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
