'use client';

/**
 * MapsExportCard
 * Lets a citizen pull the PHIPRO food-hygiene-grade list into the maps app of
 * their choice. Implements three industrial-standard share modes:
 *
 *   1. "Open in Maps"   — `geo:` deep-link (Android / iOS native maps app)
 *                         with a https://www.google.com/maps fallback on desktop.
 *                         For a SINGLE shop pass `lat`/`lng` or just an `address`.
 *   2. "Download KML"   — Generates a Keyhole Markup Language file from the current
 *                         filtered list. User imports it once into mymaps.google.com
 *                         to see every PHIPRO-verified shop as a Google "My Map" layer.
 *   3. "Embed on site"  — Reveals a copy-to-clipboard <iframe> snippet so any
 *                         external website (e.g. a chamber-of-commerce page)
 *                         can embed the live PHIPRO map.
 */

import { useState } from 'react';
import { toast } from 'sonner';
import { Map as MapIcon, Download, Code2, Copy, ExternalLink, X } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export interface MapsExportPremise {
  id: string;
  name: string;
  address: string;
  grade: string;
  score?: number;
  lat?: number;
  lng?: number;
  type?: string;
  lastInspection?: string;
}

const APP_ORIGIN = typeof window !== 'undefined' ? window.location.origin : 'https://phipro-lk.vercel.app';

function xmlEscape(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

function gradePinHex(grade: string): string {
  return grade === 'A' ? '10b981' : grade === 'B' ? 'f59e0b' : 'ef4444';
}

/** Build a Google Maps URL — uses lat/lng if present, otherwise address search. */
export function googleMapsUrl(p: { lat?: number; lng?: number; address: string; name: string }): string {
  if (p.lat != null && p.lng != null) {
    return `https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}`;
  }
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name} ${p.address}`)}`;
}

/** Best-effort deep-link: native maps on mobile, https fallback elsewhere. */
export function openInMaps(p: { lat?: number; lng?: number; address: string; name: string }): void {
  if (typeof window === 'undefined') return;
  const ua = navigator.userAgent;
  const isIOS = /iPad|iPhone|iPod/.test(ua);
  const isAndroid = /Android/.test(ua);
  if (p.lat != null && p.lng != null) {
    if (isIOS) { window.location.href = `maps://?q=${p.lat},${p.lng}`; return; }
    if (isAndroid) { window.location.href = `geo:${p.lat},${p.lng}?q=${p.lat},${p.lng}(${encodeURIComponent(p.name)})`; return; }
  }
  window.open(googleMapsUrl(p), '_blank', 'noopener,noreferrer');
}

function buildKml(items: MapsExportPremise[]): string {
  const placemarks = items
    .filter((p) => p.lat != null && p.lng != null)
    .map((p) => {
      const desc =
        `<p><b>Grade ${xmlEscape(p.grade)}</b>` +
        (p.score != null ? ` &middot; Score ${p.score}/100` : '') + '</p>' +
        `<p>${xmlEscape(p.address)}</p>` +
        (p.lastInspection ? `<p>Last inspection: ${xmlEscape(p.lastInspection)}</p>` : '') +
        `<p>Verified by PHIPRO &middot; <a href="${APP_ORIGIN}/public/verify">verify here</a></p>`;
      return `
    <Placemark>
      <name>${xmlEscape(p.name)}</name>
      <description><![CDATA[${desc}]]></description>
      <styleUrl>#grade${p.grade}</styleUrl>
      <Point><coordinates>${p.lng},${p.lat},0</coordinates></Point>
    </Placemark>`;
    }).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>PHIPRO - Food Hygiene Grades (Sri Lanka)</name>
    <description>Verified food premises with hygiene grade A/B/C - generated by PHI-PRO (${APP_ORIGIN}). Import this file at mymaps.google.com.</description>
    <Style id="gradeA"><IconStyle><color>ff00b884</color><Icon><href>https://maps.google.com/mapfiles/kml/paddle/grn-circle.png</href></Icon></IconStyle></Style>
    <Style id="gradeB"><IconStyle><color>ff0badf5</color><Icon><href>https://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon></IconStyle></Style>
    <Style id="gradeC"><IconStyle><color>ff5252ef</color><Icon><href>https://maps.google.com/mapfiles/kml/paddle/red-circle.png</href></Icon></IconStyle></Style>${placemarks}
  </Document>
</kml>`;
}

function downloadKml(items: MapsExportPremise[]): void {
  const withCoords = items.filter((p) => p.lat != null && p.lng != null);
  if (withCoords.length === 0) {
    toast.error('No premises have coordinates yet.', {
      description: 'KML needs lat/lng. Field officers add coordinates during inspection — this list will populate as inspections complete.',
    });
    return;
  }
  const xml = buildKml(items);
  const blob = new Blob([xml], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `phipro-food-grades-${new Date().toISOString().slice(0, 10)}.kml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  toast.success(`Downloaded ${withCoords.length} premises as KML`, {
    description: 'Open mymaps.google.com → "Create a new map" → Import → select this file.',
    duration: 6000,
  });
}

const EMBED_SNIPPET = (origin: string) => `<iframe
  src="${origin}/public/food-grades"
  width="100%" height="640"
  style="border:0;border-radius:12px"
  title="PHIPRO Food Hygiene Grades"
  loading="lazy"
  referrerpolicy="strict-origin-when-cross-origin">
</iframe>`;

interface Props {
  premises: MapsExportPremise[];
  /** Show the "Open in Google Maps" button (only sensible when premises have coords) */
  showOpenAll?: boolean;
}

export function MapsExportCard({ premises, showOpenAll = true }: Props) {
  const [embedOpen, setEmbedOpen] = useState(false);
  const snippet = EMBED_SNIPPET(APP_ORIGIN);

  const copyEmbed = async () => {
    try {
      await navigator.clipboard.writeText(snippet);
      toast.success('Embed snippet copied');
    } catch {
      toast.error('Copy failed — select the text manually');
    }
  };

  const openAllInMaps = () => {
    const first = premises.find((p) => p.lat != null && p.lng != null);
    if (first) {
      openInMaps(first);
    } else {
      window.open('https://www.google.com/maps/search/?api=1&query=food+premises+sri+lanka', '_blank', 'noopener,noreferrer');
    }
  };

  return (
    <Card className="border-blue-100 dark:border-blue-900/40">
      <CardContent className="p-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-start gap-3">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-100 dark:bg-blue-950/50">
              <MapIcon className="h-5 w-5 text-blue-700 dark:text-blue-300" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-900 dark:text-white">Use this map elsewhere</p>
              <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">
                Open in Google/Apple Maps, download as KML for &ldquo;My Maps&rdquo;, or embed on your site.
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {showOpenAll && (
              <Button size="sm" variant="outline" onClick={openAllInMaps} className="gap-1.5">
                <ExternalLink className="h-3.5 w-3.5" />
                Open in Maps
              </Button>
            )}
            <Button size="sm" variant="outline" onClick={() => downloadKml(premises)} className="gap-1.5">
              <Download className="h-3.5 w-3.5" />
              Download KML
            </Button>
            <Button size="sm" variant="outline" onClick={() => setEmbedOpen((v) => !v)} className="gap-1.5">
              <Code2 className="h-3.5 w-3.5" />
              {embedOpen ? 'Hide embed' : 'Embed on site'}
            </Button>
          </div>
        </div>

        {embedOpen && (
          <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-900/60">
            <div className="flex items-center justify-between">
              <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">
                Copy &amp; paste into any web page
              </p>
              <div className="flex items-center gap-1">
                <Button size="sm" variant="ghost" onClick={copyEmbed} className="h-7 gap-1 px-2 text-[11px]">
                  <Copy className="h-3 w-3" />
                  Copy
                </Button>
                <Button size="sm" variant="ghost" onClick={() => setEmbedOpen(false)} className="h-7 w-7 p-0">
                  <X className="h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
            <pre className="mt-2 overflow-x-auto rounded-md bg-slate-950 p-3 text-[11px] leading-relaxed text-slate-100">
              <code>{snippet}</code>
            </pre>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
