'use client';

/**
 * MapsExportCard
 * Three one-click actions for citizens, partners and developers:
 *
 *   1. "Open in Maps"     — `geo:`/`maps:` deep-link on iOS/Android, Google Maps on desktop.
 *   2. "Copy embed code"  — One-click copy of an <iframe> snippet for any HTML page / CMS.
 *   3. "Preview"          — Opens the embeddable view in a new window so the user can
 *                           verify what gets embedded before pasting.
 *   4. "Download HTML"    — Downloads a standalone, ready-to-host single-file HTML wrapper
 *                           (header + iframe + footer) for partners who want a turn-key page.
 */

import { toast } from 'sonner';
import { Map as MapIcon, Download, Copy, ExternalLink, Eye, FileCode2 } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

export interface MapsExportPremise {
  id: string;
  name: string;
  address: string;
  grade: string;
  score?: number;
  lat?: number;
  lng?: number;
  type?: string;
  lastInspection?: string;
}

const APP_ORIGIN = typeof window !== 'undefined' ? window.location.origin : 'https://phipro-lk.vercel.app';

function xmlEscape(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

/** Build a Google Maps URL — uses lat/lng if present, otherwise address search. */
export function googleMapsUrl(p: { lat?: number; lng?: number; address: string; name: string }): string {
  if (p.lat != null && p.lng != null) {
    return `https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}`;
  }
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name} ${p.address}`)}`;
}

/** Best-effort deep-link: native maps on mobile, https fallback elsewhere. */
export function openInMaps(p: { lat?: number; lng?: number; address: string; name: string }): void {
  if (typeof window === 'undefined') return;
  const ua = navigator.userAgent;
  const isIOS = /iPad|iPhone|iPod/.test(ua);
  const isAndroid = /Android/.test(ua);
  if (p.lat != null && p.lng != null) {
    if (isIOS) { window.location.href = `maps://?q=${p.lat},${p.lng}`; return; }
    if (isAndroid) { window.location.href = `geo:${p.lat},${p.lng}?q=${p.lat},${p.lng}(${encodeURIComponent(p.name)})`; return; }
  }
  window.open(googleMapsUrl(p), '_blank', 'noopener,noreferrer');
}

function buildKml(items: MapsExportPremise[]): string {
  const placemarks = items
    .filter((p) => p.lat != null && p.lng != null)
    .map((p) => {
      const desc =
        `<p><b>Grade ${xmlEscape(p.grade)}</b>` +
        (p.score != null ? ` &middot; Score ${p.score}/100` : '') + '</p>' +
        `<p>${xmlEscape(p.address)}</p>` +
        (p.lastInspection ? `<p>Last inspection: ${xmlEscape(p.lastInspection)}</p>` : '') +
        `<p>Verified by PHIPRO &middot; <a href="${APP_ORIGIN}/public/verify">verify here</a></p>`;
      return `
    <Placemark>
      <name>${xmlEscape(p.name)}</name>
      <description><![CDATA[${desc}]]></description>
      <styleUrl>#grade${p.grade}</styleUrl>
      <Point><coordinates>${p.lng},${p.lat},0</coordinates></Point>
    </Placemark>`;
    }).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>PHIPRO - Food Hygiene Grades (Sri Lanka)</name>
    <description>Verified food premises with hygiene grade A/B/C - generated by PHI-PRO (${APP_ORIGIN}). Import this file at mymaps.google.com.</description>
    <Style id="gradeA"><IconStyle><Icon><href>https://maps.google.com/mapfiles/kml/paddle/grn-circle.png</href></Icon></IconStyle></Style>
    <Style id="gradeB"><IconStyle><Icon><href>https://maps.google.com/mapfiles/kml/paddle/ylw-circle.png</href></Icon></IconStyle></Style>
    <Style id="gradeC"><IconStyle><Icon><href>https://maps.google.com/mapfiles/kml/paddle/red-circle.png</href></Icon></IconStyle></Style>${placemarks}
  </Document>
</kml>`;
}

function downloadKml(items: MapsExportPremise[]): void {
  const withCoords = items.filter((p) => p.lat != null && p.lng != null);
  if (withCoords.length === 0) {
    toast.error('No premises have coordinates yet.', {
      description: 'KML needs lat/lng. Coordinates are captured during field inspection.',
    });
    return;
  }
  const xml = buildKml(items);
  const blob = new Blob([xml], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `phipro-food-grades-${new Date().toISOString().slice(0, 10)}.kml`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  toast.success(`Downloaded ${withCoords.length} premises as KML`, {
    description: 'Open mymaps.google.com → Create a new map → Import → select this file.',
    duration: 6000,
  });
}

const EMBED_SNIPPET = (origin: string) => `<iframe
  src="${origin}/public/food-grades"
  width="100%" height="640"
  style="border:0;border-radius:12px"
  title="PHIPRO Food Hygiene Grades"
  loading="lazy"
  referrerpolicy="strict-origin-when-cross-origin">
</iframe>`;

const STANDALONE_HTML = (origin: string) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>PHIPRO Food Hygiene Grades</title>
<style>
  body { margin:0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background:#f8fafc; }
  header { background:#1e3a8a; color:white; padding:16px 24px; }
  header h1 { margin:0; font-size:16px; font-weight:700; letter-spacing:.02em; }
  header p { margin:4px 0 0; font-size:12px; opacity:.85; }
  .wrap { padding:16px; }
  iframe { width:100%; height:640px; border:0; border-radius:12px; box-shadow:0 1px 3px rgba(0,0,0,.08); }
  footer { padding:12px 24px; font-size:11px; color:#64748b; text-align:center; }
  footer a { color:#1e3a8a; text-decoration:none; }
</style>
</head>
<body>
<header>
  <h1>PHIPRO &mdash; Food Hygiene Grades (Sri Lanka)</h1>
  <p>Live data from the Public Health Inspectors&rsquo; Union of Sri Lanka</p>
</header>
<main class="wrap">
  <iframe
    src="${origin}/public/food-grades"
    title="PHIPRO Food Hygiene Grades"
    loading="lazy"
    referrerpolicy="strict-origin-when-cross-origin"></iframe>
</main>
<footer>
  Powered by <a href="${origin}" target="_blank" rel="noopener">PHI-PRO</a> &middot; Ministry of Health, Sri Lanka
</footer>
</body>
</html>`;

function downloadHtml(origin: string): void {
  const html = STANDALONE_HTML(origin);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `phipro-food-grades-embed-${new Date().toISOString().slice(0, 10)}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  toast.success('Standalone HTML downloaded', {
    description: 'Open the file in any browser or upload it to your website — the live map embeds automatically.',
    duration: 6000,
  });
}

interface Props {
  premises: MapsExportPremise[];
  /** Show the "Open in Google Maps" button (only sensible when premises have coords) */
  showOpenAll?: boolean;
}

export function MapsExportCard({ premises, showOpenAll = true }: Props) {
  const snippet = EMBED_SNIPPET(APP_ORIGIN);

  const copyEmbed = async () => {
    try {
      await navigator.clipboard.writeText(snippet);
      toast.success('Embed code copied', {
        description: 'Paste into any HTML page or CMS rich-text block. Works in WordPress, Wix, Squarespace, Notion, Webflow, plain HTML.',
        duration: 6000,
      });
    } catch {
      toast.error('Copy failed — select the snippet manually below');
    }
  };

  const previewEmbed = () => {
    window.open(`${APP_ORIGIN}/public/food-grades`, '_blank', 'noopener,noreferrer,width=900,height=720');
  };

  const openAllInMaps = () => {
    const first = premises.find((p) => p.lat != null && p.lng != null);
    if (first) {
      openInMaps(first);
    } else {
      window.open('https://www.google.com/maps/search/?api=1&query=food+premises+sri+lanka', '_blank', 'noopener,noreferrer');
    }
  };

  return (
    <Card className="border-blue-200 bg-gradient-to-br from-blue-50/60 to-white shadow-sm dark:border-blue-900/40 dark:from-blue-950/30 dark:to-slate-950">
      <CardContent className="p-5">
        {/* Header + primary actions on a single line on desktop */}
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex items-start gap-3">
            <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-100 dark:bg-blue-950/50">
              <MapIcon className="h-5 w-5 text-blue-700 dark:text-blue-300" />
            </div>
            <div className="min-w-0">
              <p className="text-sm font-bold text-slate-900 dark:text-white">Use this map elsewhere</p>
              <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">
                Open in a maps app, embed on any website, or download a ready-to-host HTML page.
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2 lg:flex-nowrap">
            {showOpenAll && (
              <Button
                size="sm"
                variant="outline"
                onClick={openAllInMaps}
                className="h-9 gap-1.5 whitespace-nowrap text-xs"
              >
                <ExternalLink className="h-3.5 w-3.5" />
                Open in Maps
              </Button>
            )}
            <Button
              size="sm"
              variant="outline"
              onClick={() => downloadKml(premises)}
              className="h-9 gap-1.5 whitespace-nowrap text-xs"
            >
              <Download className="h-3.5 w-3.5" />
              Download KML
            </Button>
            <Button
              size="sm"
              onClick={copyEmbed}
              className="h-9 gap-1.5 whitespace-nowrap bg-blue-700 text-xs text-white shadow-sm hover:bg-blue-800"
            >
              <Copy className="h-3.5 w-3.5" />
              Copy embed code
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={previewEmbed}
              className="h-9 gap-1.5 whitespace-nowrap text-xs"
            >
              <Eye className="h-3.5 w-3.5" />
              Preview
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={() => downloadHtml(APP_ORIGIN)}
              className="h-9 gap-1.5 whitespace-nowrap text-xs"
            >
              <FileCode2 className="h-3.5 w-3.5" />
              Download HTML
            </Button>
          </div>
        </div>

        {/* Collapsible raw snippet — opt-in only */}
        <details className="mt-4 rounded-xl border border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900/40">
          <summary className="cursor-pointer select-none px-4 py-2.5 text-[11px] font-semibold uppercase tracking-wider text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200">
            View raw embed snippet
          </summary>
          <pre className="overflow-x-auto rounded-b-xl bg-slate-950 p-3 text-[11px] leading-relaxed text-slate-100">
            <code>{snippet}</code>
          </pre>
        </details>
      </CardContent>
    </Card>
  );
}
