// ============================================================================
// Payment receipt PDF — generated client-side with @react-pdf/renderer (already
// a dependency). downloadPaymentReceipt() lazy-imports the library so it isn't
// in the main bundle. Used after a permit-fee payment on the public portal.
// ============================================================================

export interface ReceiptData {
  paymentRef: string;
  serviceType: string;
  referenceId?: string | null;
  payerName: string;
  phone: string;
  email?: string | null;
  amount: number;
  currency?: string;
  channel: string;
  status: string;
  dateISO: string;
}

export async function downloadPaymentReceipt(data: ReceiptData): Promise<void> {
  const { pdf, Document, Page, Text, View, StyleSheet } = await import('@react-pdf/renderer');

  const s = StyleSheet.create({
    page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica', color: '#0f172a' },
    header: { borderBottomWidth: 2, borderBottomColor: '#1e4ba6', paddingBottom: 12, marginBottom: 18 },
    org: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: '#1e4ba6' },
    sub: { fontSize: 9, color: '#475569', marginTop: 2 },
    title: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
    badge: { fontSize: 9, color: '#15803d', fontFamily: 'Helvetica-Bold' },
    row: { flexDirection: 'row', marginBottom: 7 },
    label: { width: 150, color: '#64748b' },
    value: { flex: 1, fontFamily: 'Helvetica-Bold' },
    amountBox: { marginTop: 14, padding: 12, backgroundColor: '#f1f5f9', borderRadius: 4 },
    amount: { fontSize: 20, fontFamily: 'Helvetica-Bold' },
    foot: { position: 'absolute', bottom: 32, left: 40, right: 40, fontSize: 8, color: '#94a3b8', borderTopWidth: 1, borderTopColor: '#e2e8f0', paddingTop: 8 },
  });

  const d = new Date(data.dateISO);
  const fmtDate = isNaN(d.getTime()) ? data.dateISO : d.toLocaleString('en-LK');
  const cur = data.currency ?? 'LKR';

  const Doc = (
    <Document title={`Receipt ${data.paymentRef}`}>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.org}>The Public Health Inspector&apos;s Union of Sri Lanka</Text>
          <Text style={s.sub}>673 Maradana Road, Colombo 01000 · www.phi.lk · PHI-PRO Digital Enforcement Hub</Text>
        </View>

        <Text style={s.title}>Payment Receipt</Text>
        <Text style={s.badge}>{data.status === 'completed' ? 'PAID' : data.status.toUpperCase().replace(/_/g, ' ')}</Text>

        <View style={{ marginTop: 18 }}>
          <View style={s.row}><Text style={s.label}>Receipt / Payment Ref</Text><Text style={s.value}>{data.paymentRef}</Text></View>
          <View style={s.row}><Text style={s.label}>Date</Text><Text style={s.value}>{fmtDate}</Text></View>
          <View style={s.row}><Text style={s.label}>Service</Text><Text style={s.value}>{data.serviceType}</Text></View>
          {data.referenceId ? <View style={s.row}><Text style={s.label}>Permit / Reference</Text><Text style={s.value}>{data.referenceId}</Text></View> : null}
          <View style={s.row}><Text style={s.label}>Paid by</Text><Text style={s.value}>{data.payerName}</Text></View>
          <View style={s.row}><Text style={s.label}>Phone</Text><Text style={s.value}>{data.phone}</Text></View>
          {data.email ? <View style={s.row}><Text style={s.label}>Email</Text><Text style={s.value}>{data.email}</Text></View> : null}
          <View style={s.row}><Text style={s.label}>Channel</Text><Text style={s.value}>{data.channel}</Text></View>
        </View>

        <View style={s.amountBox}>
          <Text style={{ fontSize: 9, color: '#64748b' }}>Amount paid</Text>
          <Text style={s.amount}>{cur} {data.amount.toLocaleString('en-LK', { minimumFractionDigits: 2 })}</Text>
        </View>

        <Text style={{ marginTop: 18, fontSize: 9, color: '#64748b' }}>
          Keep this receipt. A PHI officer will use the payment reference to confirm receipt and proceed with your
          inspection / certificate. This document was generated by PHI-PRO; verify its authenticity at /public/verify.
        </Text>

        <Text style={s.foot}>PHI-PRO · Ministry of Health, Sri Lanka · This is a system-generated receipt and does not require a signature.</Text>
      </Page>
    </Document>
  );

  const blob = await pdf(Doc).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `PHI-PRO-receipt-${data.paymentRef}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
